# Generated by Django 3.1.1 on 2020-10-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='brief',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
