# Generated by Django 3.1.1 on 2020-10-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20201003_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
