# Generated by Django 3.1.1 on 2020-10-04 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_testimony'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
