# Generated by Django 3.1.1 on 2020-10-04 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_testimony_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimony',
            old_name='text',
            new_name='feedback',
        ),
    ]
